import { createElement } from '@lwc/engine-dom';
import Inv_LWC001_PopupReminderController from 'c/inv_LWC001_PopupReminderController';

describe('c-inv-l-w-c-001-popup-reminder-controller', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-inv-l-w-c-001-popup-reminder-controller', {
            is: Inv_LWC001_PopupReminderController
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});